"use client";

import { useMemo, useState } from "react";
import { certificationSummary, runCertificationChecks } from "@/lib/production-certification";

export default function CertificationPage() {
  const [run, setRun] = useState(false);
  const checks = useMemo(() => run ? runCertificationChecks() : [], [run]);
  const summary = certificationSummary(checks);
  return <main className="main">
    <div className="topbar"><div><div className="eyebrow">Phase 20 · Final Readiness Gate</div><h1>Production Certification</h1></div><div className="status"><span className="dot" /> CERTIFICATION CONTROL</div></div>
    <section className="grid"><div className="card"><div className="metric-label">Checks</div><div className="metric">{summary.total}</div><div className="metric-note">Final readiness controls</div></div><div className="card"><div className="metric-label">Passed</div><div className="metric">{summary.passed}</div><div className="metric-note">Validated foundations</div></div><div className="card"><div className="metric-label">Warnings</div><div className="metric">{summary.warnings}</div><div className="metric-note">Deployment requirements</div></div><div className="card"><div className="metric-label">Final Status</div><div className="metric">{run ? (summary.certified ? "CERTIFIED" : "NOT CERTIFIED") : "NOT RUN"}</div><div className="metric-note">A blocker prevents certification</div></div></section>
    <section className="card preflight-card"><div className="card-title"><span>Final Certification Gate</span><span className="badge">READINESS ONLY</span></div><p className="strategy-help">Run the final assessment across technical, security, financial, custody, compliance, operations and recovery domains. A PASS here is a technical readiness result, not a legal, regulatory or financial-services license.</p><button className="primary-button" onClick={() => setRun(true)}>Run Final Certification</button>{run && <div className="preflight-list">{checks.map(check => <div className="finding" key={check.id}><span className={`severity severity-${check.status.toLowerCase()}`}>{check.status}</span><div><strong>{check.domain} · {check.name}</strong><p>{check.detail}</p>{check.blocking && <span className="warning">Blocking gate</span>}</div></div>)}</div>}</section>
    <section className="workspace"><div className="card"><div className="card-title"><span>Certification Decision</span><span className="badge">{run ? (summary.certified ? "READY" : "BLOCKED") : "PENDING"}</span></div>{run ? <div className="list"><div className="list-row"><span>Passed</span><strong>{summary.passed}</strong></div><div className="list-row"><span>Warnings</span><strong>{summary.warnings}</strong></div><div className="list-row"><span>Blocked</span><strong>{summary.blocked}</strong></div><div className="list-row"><span>Blocking warnings</span><strong>{summary.blockingWarnings}</strong></div><div className="list-row"><span>Production certification</span><strong>{summary.certified ? "ELIGIBLE" : "NOT ELIGIBLE"}</strong></div></div> : <div className="empty-state">Run the assessment to calculate the final decision.</div>}</div><div className="card"><div className="card-title"><span>Final Safety Boundary</span><span className="badge">ENFORCED</span></div><div className="list"><div className="list-row"><span>Research mode</span><strong>Enabled</strong></div><div className="list-row"><span>Live rug execution</span><strong>Disabled</strong></div><div className="list-row"><span>Application-held signing keys</span><strong>Disabled</strong></div><div className="list-row"><span>Automatic balance mutation</span><strong>Disabled</strong></div><div className="list-row"><span>Real-money activation</span><strong>Not provided</strong></div></div></div></section>
    <p className="footer-note">Phase 20 is a readiness gate, not a license or guarantee. Real-money custody requires appropriate legal and regulatory authorization, institutional custody/payment partners, production security controls and independently verified operational processes.</p>
  </main>;
}
