"use client";

import { useMemo, useState } from "react";
import { analyzeToken, riskScore, SecurityInput, Severity } from "@/lib/security-research";

const defaults: SecurityInput = { mint: "", mintAuthority: true, freezeAuthority: false, supply: 1_000_000, decimals: 9, holders: 120, liquidity: 40_000, topHolderPct: 18, metadataMutable: true };
const severityOrder: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];

export default function SecurityResearchPage() {
  const [input, setInput] = useState(defaults);
  const [findings, setFindings] = useState<ReturnType<typeof analyzeToken>>([]);
  const [report, setReport] = useState("");
  const score = useMemo(() => riskScore(findings), [findings]);
  const update = <K extends keyof SecurityInput>(key: K, value: SecurityInput[K]) => setInput((current) => ({ ...current, [key]: value }));

  function scan() { setFindings(analyzeToken(input)); setReport(""); }
  function generateReport() {
    const lines = [`RUG PULL LAB — SECURITY RESEARCH REPORT`, `Mint: ${input.mint || "not supplied"}`, `Risk score: ${score}/100`, `Findings: ${findings.length}`, "", ...findings.map((f) => `[${f.severity}] ${f.title}\n${f.detail}\nRecommendation: ${f.recommendation}`)];
    setReport(lines.join("\n\n"));
  }
  function downloadReport() { if (!report) return; const blob = new Blob([report], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "rug-pull-lab-security-report.txt"; a.click(); URL.revokeObjectURL(url); }

  return <main className="main"><div className="topbar"><div><div className="eyebrow">Phase 7 · Security Research</div><h1>Security Analyzer</h1></div><div className="status"><span className="dot" /> READ-ONLY RESEARCH</div></div>
    <section className="grid"><div className="card"><div className="metric-label">Risk Score</div><div className="metric">{score}/100</div><div className="metric-note">Heuristic research score</div></div><div className="card"><div className="metric-label">Findings</div><div className="metric">{findings.length}</div><div className="metric-note">Current snapshot</div></div><div className="card"><div className="metric-label">High / Critical</div><div className="metric">{findings.filter((f) => f.severity === "HIGH" || f.severity === "CRITICAL").length}</div><div className="metric-note">Priority findings</div></div><div className="card"><div className="metric-label">Execution</div><div className="metric">NONE</div><div className="metric-note">Analyzer cannot move assets</div></div></section>
    <section className="workspace strategy-layout"><div className="card"><div className="card-title"><span>Token Risk Inputs</span><span className="badge">LOCAL SNAPSHOT</span></div><div className="form-grid"><label>Mint address<input value={input.mint} onChange={(e) => update("mint", e.target.value)} placeholder="Optional public mint address" /></label><label>Supply<input type="number" min="0" value={input.supply} onChange={(e) => update("supply", Number(e.target.value))} /></label><label>Decimals<input type="number" min="0" max="18" value={input.decimals} onChange={(e) => update("decimals", Number(e.target.value))} /></label><label>Holders<input type="number" min="0" value={input.holders} onChange={(e) => update("holders", Number(e.target.value))} /></label><label>Tracked liquidity<input type="number" min="0" value={input.liquidity} onChange={(e) => update("liquidity", Number(e.target.value))} /></label><label>Top holder %<input type="number" min="0" max="100" step="0.1" value={input.topHolderPct} onChange={(e) => update("topHolderPct", Number(e.target.value))} /></label></div><div className="security-toggles"><label><input type="checkbox" checked={input.mintAuthority} onChange={(e) => update("mintAuthority", e.target.checked)} /> Mint authority active</label><label><input type="checkbox" checked={input.freezeAuthority} onChange={(e) => update("freezeAuthority", e.target.checked)} /> Freeze authority active</label><label><input type="checkbox" checked={input.metadataMutable} onChange={(e) => update("metadataMutable", e.target.checked)} /> Metadata mutable</label></div><button className="primary-button" onClick={scan}>Run security analysis</button></div>
      <div className="card"><div className="card-title"><span>Risk Methodology</span><span className="badge">HEURISTICS</span></div><div className="list"><div className="list-row"><span>Authority analysis</span><strong>Enabled</strong></div><div className="list-row"><span>Holder concentration</span><strong>Enabled</strong></div><div className="list-row"><span>Liquidity depth</span><strong>Enabled</strong></div><div className="list-row"><span>Metadata controls</span><strong>Enabled</strong></div><div className="list-row"><span>Automated execution</span><strong>Disabled</strong></div></div><p className="muted strategy-help">The score is an investigative aid, not a guarantee that a token is safe or malicious. Validate findings against on-chain evidence.</p></div></section>
    <section className="card token-table-card"><div className="card-title"><span>Findings</span><span className="badge">{findings.length ? `${score}/100 RISK` : "NOT SCANNED"}</span></div>{findings.length === 0 ? <div className="empty-state">Run an analysis to generate prioritized security findings.</div> : <div className="security-findings">{severityOrder.flatMap((severity) => findings.filter((f) => f.severity === severity)).map((f) => <article className="finding" key={f.id}><div className={`severity severity-${f.severity.toLowerCase()}`}>{f.severity}</div><div><strong>{f.title}</strong><p>{f.detail}</p><span className="muted">Recommendation: {f.recommendation}</span></div></article>)}</div>}</section>
    <section className="card"><div className="card-title"><span>Research Report</span><div className="strategy-actions"><button className="secondary" disabled={!findings.length} onClick={generateReport}>Generate report</button><button className="primary" disabled={!report} onClick={downloadReport}>Download TXT</button></div></div>{report ? <pre className="report-preview">{report}</pre> : <div className="empty-state">Generate a report after analysis to create a portable research record.</div>}</section>
    <p className="footer-note">Security Research is read-only. It performs heuristic analysis and report generation only; it cannot blacklist sellers, drain liquidity, dump assets, or execute a live public-market rug operation.</p>
  </main>;
}
